let employee =[{"id":1,"name":"Harman","gender":"Male"},
{"id":2,"name":"Conway","gender":"Male"},
{"id":3,"name":"Pincas","gender":"Male"},
{"id":4,"name":"Reggie","gender":"Male"},
{"id":5,"name":"Royal","gender":"Male"},
{"id":6,"name":"Aubrette","gender":"Female"},
{"id":7,"name":"Raviv","gender":"Male"},
{"id":8,"name":"Claudio","gender":"Male"},
{"id":9,"name":"Rivkah","gender":"Female"},
{"id":10,"name":"Taffy","gender":"Female"},
{"id":11,"name":"Gustav","gender":"Male"},
{"id":12,"name":"Lazare","gender":"Male"},
{"id":13,"name":"Petr","gender":"Bigender"},
{"id":14,"name":"Sydel","gender":"Female"},
{"id":15,"name":"Tripp","gender":"Male"},
{"id":16,"name":"Lorenzo","gender":"Male"},
{"id":17,"name":"Benedetto","gender":"Male"},
{"id":18,"name":"Charmine","gender":"Female"},
{"id":19,"name":"Constancia","gender":"Female"},
{"id":20,"name":"Audie","gender":"Female"},
{"id":21,"name":"Mark","gender":"Male"},
{"id":22,"name":"Shepperd","gender":"Male"},
{"id":23,"name":"Cherlyn","gender":"Female"},
{"id":24,"name":"Fionnula","gender":"Female"},
{"id":25,"name":"Wilhelm","gender":"Male"},
{"id":26,"name":"Kalila","gender":"Female"},
{"id":27,"name":"Audie","gender":"Agender"},
{"id":28,"name":"Ardith","gender":"Female"},
{"id":29,"name":"Robinette","gender":"Female"},
{"id":30,"name":"Daven","gender":"Male"},
{"id":31,"name":"Fernando","gender":"Male"},
{"id":32,"name":"Grantley","gender":"Male"},
{"id":33,"name":"Ursulina","gender":"Female"},
{"id":34,"name":"La verne","gender":"Female"},
{"id":35,"name":"Joya","gender":"Female"},
{"id":36,"name":"Melisenda","gender":"Female"},
{"id":37,"name":"Celestia","gender":"Female"},
{"id":38,"name":"Scottie","gender":"Male"},
{"id":39,"name":"Napoleon","gender":"Male"},
{"id":40,"name":"Job","gender":"Male"},
{"id":41,"name":"Dacy","gender":"Female"},
{"id":42,"name":"Melamie","gender":"Female"},
{"id":43,"name":"Guillermo","gender":"Male"},
{"id":44,"name":"Jacqueline","gender":"Female"},
{"id":45,"name":"Odele","gender":"Female"},
{"id":46,"name":"Gwyneth","gender":"Female"},
{"id":47,"name":"Susette","gender":"Female"},
{"id":48,"name":"Katerina","gender":"Female"},
{"id":49,"name":"Bernie","gender":"Female"},
{"id":50,"name":"Sterne","gender":"Male"}] 

for(emp of employee){
    if(emp.gender === "Male"){
    console.log("Emp Id", emp.id, "Emp Name", emp.name, "Emp Gender", emp.gender);
    }
}